### PR TITLE
make compatible with python 3

### PR DESCRIPTION
**Pull request by jrhite**
make compatible with python 3

### CODE REVIEW

**Comment by rynbrd** [comment]
This seems like a round-about method of retrieving the exception. Shouldn't the `except Exception as e` syntax work in Python 3?

**Comment by jrhite** [comment]
The syntax you describe is Python 3 style, which is correct. The `as` syntax has also been back ported to python 2.6+.

You can see the Python 2 to 3 porting guidelines on exceptions here:

[Capturing the Currently Raised Exception](https://docs.python.org/3/howto/pyporting.html#capturing-the-currently-raised-exception)

Per the above link, using the `as` syntax

```
try:
    raise Exception()
except Exception as exc:
    # Current exception is 'exc'.
    # In Python 3, 'exc' is restricted to the block; in Python 2.6/2.7 it will "leak".
    pass
```

will _leak_ the the `exc` variable (ie: it will be visible outside the scope of the `except` block).

So I choose the more roundabout way shown in the docs because it seemed safer.

```
try:
    raise Exception()
except Exception:
    import sys
    exc = sys.exc_info()[1]
    # Current exception is 'exc'.
    pass
```

**Comment by roboslone** [comment]
Bump! Pull request seems okay, dying for python3 support here :(

**Comment by amcgregor** [comment]
Given this still hasn't been accepted (4-5 years…) there apparently is still time to chime in that the `as e` syntax is preferable to `exc_info` mangling.  The stated reason of scope fails for me locally:

screen shot 2019-02-12 at 12 47 26 pm

Both leak under CPython 2.7, at least.  Under 3.7.2, the default processing of exceptions is to treat them as strings, apparently, resulting in `" vs "` output, which is silly.  However, under 3.7.2, `exc` as constructed via the "workaround" is what leaks, not the `as e`!  (The **reverse** of the previously stated leakage.)

Additionally, I see hypothetically leaking variables as a silly reason to pick the less legible (and non-standard / discouraged) form instead of simply adding a `del` of that label if it _really_ matters.  (_Explicit is better than implicit._)  Because that syntax was back-ported, it is in no way safer to avoid it than to use it; it only makes the code harder to read, and doesn't even need a `__future__` flag import to make use of.

**Comment by amcgregor** [comment]
@BlueDragonX Thank you so much for the attention on this PR after so long!  :D  One other niggling detail (given you have issues turned off, I can't properly file this), from upstream: [Sensitive information exposure via logs.](https://github.com/bwmcadams/mongodb_beaker/issues/11) (in your fork, on [line 248](https://github.com/BlueDragonX/beaker_mongodb/blob/master/beaker_mongodb/__init__.py#L248))

**Pull request merged**
